apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmdeployfromgitops2
  namespace: openshift-gitops
spec:
  destination:
    namespace: deployvm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployvm/
    repoURL: https://github.com/KaitoInaba/ocpv-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true